---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pizzastore.dereksu.dev
  resources:
  - pizzas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pizzastore.dereksu.dev
  resources:
  - pizzas/finalizers
  verbs:
  - update
- apiGroups:
  - pizzastore.dereksu.dev
  resources:
  - pizzas/status
  verbs:
  - get
  - patch
  - update
